### ISSUE TITLE
Document Authentication options

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#107]
Need more info about those:

| Command line | Env var | YAML | Description |
| -------------- | -------- | ----- | ------------ |
| -AuthenticationType<br/>--authentication-type=VALUE<br/> | AUTHENTICATION_TYPE | AuthenticationType | The type of authentication to use. (Default: internal) |
| -AuthenticationConfig<br/>--authentication-config=VALUE<br/> | AUTHENTICATION_CONFIG | AuthenticationConfig | Path to the configuration file for authentication configuration (if applicable). |

**Comment by mat-mcloughlin** [comment]
Also consider #104
