### ISSUE TITLE
Introduction page for v5 server

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#122]
https://developers.eventstore.com/server/5.0.9/server/introduction/introduction.html

## Key features
- Event streams
- Real-time subscriptions
- High availability
- Persistent subscriptions
- Server-side projections

**Comment by oskardudycz** [comment]
Currently, we have already such page https://www.eventstore.com/eventstoredb. @alexeyzimarev @mat-mcloughlin if you think that we should enhance that then feel free to reopen the issue.
