### ISSUE TITLE
Add example of writing default settings using cURL

### ISSUE THREAD

**Issue by jen20** [EventStore/documentation#128]
We currently show the JSON but not the cURL command necessary to write default settings.

**Comment by mbaldhainstream** [comment]
Is there any other way to write $settings stream once I have hard deleted it? If CURL command is not necessary to write default settings, what is another option to do so? I mean how can I prevent somebody from writing / reading events to the Event Store?

**Comment by jen20** [comment]
Once you've hard deleted a stream there's no way to write to it again short of creating a new database.

**Comment by mbaldha1990** [comment]
Ok. I got it now. So here I am attaching some files using which I created $setting stream successfully but It was not allowing me to change ACL and shows no metadata when I open that stream. Can you please give me an example for how to setup access only to "Test" user to read / write any events to Event Store? 
Created Stream using picture: 4
![4](https://cloud.githubusercontent.com/assets/13354798/8708360/70c9832c-2b09-11e5-8285-baa68687ce46.JPG)

Got Created Successful: Picture 5
![5](https://cloud.githubusercontent.com/assets/13354798/8708268/fd6cd23a-2b08-11e5-9449-4dd45be9eb04.JPG)

Was not able to access the ACL
So try to delete and recreate, Got output as: Picture
![6](https://cloud.githubusercontent.com/assets/13354798/8708382/9489452c-2b09-11e5-88d1-b11e4f588753.JPG)

So it looks like it has been hard deleted and can not create it again. 
I do not want to do the same with my new database and just want to make sure that it works the way we expect. If you can give me an example as I have asked in the beginning of this post it would be great.

Thanks

**Comment by gregoryyoung** [comment]
"So it looks like it has been hard deleted and can not create it again. "

When you hard delete a stream it is gone forever. There are some ways of
recreating it but its manual work (like hex editor or internal tool type
stuff). You won't be able to recreate it easily.

Cheers,

Greg

On Wed, Jul 15, 2015 at 8:54 PM, mbaldha1990 <notifications@github.com>
wrote:

> Ok. I got it now. So here I am attaching some files using which I created
> $setting stream successfully but It was not allowing me to change ACL and
> shows no metadata when I open that stream. Can you please give me an
> example for how to setup access only to "Test" user to read / write any
> events to Event Store?
> Created Stream using picture: 4
> [image: 4]
> <https://cloud.githubusercontent.com/assets/13354798/8708360/70c9832c-2b09-11e5-8285-baa68687ce46.JPG>
>
> Got Created Successful: Picture 5
> [image: 5]
> <https://cloud.githubusercontent.com/assets/13354798/8708268/fd6cd23a-2b08-11e5-9449-4dd45be9eb04.JPG>
>
> Was not able to access the ACL
> So try to delete and recreate, Got output as: Picture
> [image: 6]
> <https://cloud.githubusercontent.com/assets/13354798/8708382/9489452c-2b09-11e5-88d1-b11e4f588753.JPG>
>
> So it looks like it has been hard deleted and can not create it again.
> I do not want to do the same with my new database and just want to make
> sure that it works the way we expect. If you can give me an example as I
> have asked in the beginning of this post it would be great.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/128#issuecomment-121726895>
> .
>



-- 
Studying for the Turing test

**Comment by mbaldha1990** [comment]
Is there any example I can consider writing $settings stream to Event Store for authorization? I mean the one I did was not giving the access to the ACL to be modified and it says no metadata when I try to access it. I think the way I created was wrong and it was displaying all the ACL values as a JSON data. Is there any example on the Event Store Google Group or Documentation about how to write $settings stream properly?

**Comment by mbaldha1990** [comment]
Finally after lots of research I got the $settings stream created where I can also set the acl for the stream. 
See this:
![11](https://cloud.githubusercontent.com/assets/13354798/8730147/2cfdf222-2bbd-11e5-9376-64dfd4419c44.JPG)
![12](https://cloud.githubusercontent.com/assets/13354798/8730153/3339505a-2bbd-11e5-8880-b8af55bb354f.JPG)
![13](https://cloud.githubusercontent.com/assets/13354798/8730156/370bb2c2-2bbd-11e5-91ef-3a2eced3c491.JPG)
Still when I write an event from our project using .NET API it gets posted to the event store without any credentials. Let me know what am I missing in order to imply the security from TCP level using .NET API.

**Comment by gregoryyoung** [comment]
There is information showing how to use curl to set this on the doc page
for acls.

The $settings stream you post an event to and its the default. You don't
edit ITS ACL.

Greg


On Thu, Jul 16, 2015 at 7:20 PM, mbaldha1990 <notifications@github.com>
wrote:

> Finally after lots of research I got the $settings stream created where I
> can also set the acl for the stream.
> See this:
> [image: 11]
> <https://cloud.githubusercontent.com/assets/13354798/8730147/2cfdf222-2bbd-11e5-9376-64dfd4419c44.JPG>
> [image: 12]
> <https://cloud.githubusercontent.com/assets/13354798/8730153/3339505a-2bbd-11e5-8880-b8af55bb354f.JPG>
> [image: 13]
> <https://cloud.githubusercontent.com/assets/13354798/8730156/370bb2c2-2bbd-11e5-91ef-3a2eced3c491.JPG>
> Still when I write an event from our project using .NET API it gets posted
> to the event store without any credentials. Let me know what am I missing
> in order to imply the security from TCP level using .NET API.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/128#issuecomment-122026725>
> .
>



-- 
Studying for the Turing test

**Comment by mbaldha1990** [comment]
Ok. I did not assign anything in the acl and the metadata for the $settings stream looks like:
![14](https://cloud.githubusercontent.com/assets/13354798/8730391/58b974d0-2bbe-11e5-8902-e3939b3af000.JPG)

Am I going on the right track? Events are still getting added with no credentials.

**Comment by jen20** [comment]
That's NOT the `$settings` stream, that's the metadata stream for `$settings` (see the `$$$` at the start). The ACL needs to be the EVENT body (NOT the metadata) in the `$settings` stream. As per your earlier error log ensure the file actually exists, is not being interpolated by a shell etc.

**Comment by mbaldha1990** [comment]
So it should be like:
![15](https://cloud.githubusercontent.com/assets/13354798/8730537/5b33d2ea-2bbf-11e5-991a-e0cc07ae7cab.JPG)
Am I right? Now I got it under Data instead of $settings metadata stream.

**Comment by mbaldha1990** [comment]
Looks like I got something working. Now if I don't pass any credentials when I read / write any events, it will throw an ecxeption like:

System.AggregateException : One or more errors occurred.
  ----> EventStore.ClientAPI.Exceptions.AccessDeniedException : Write access denied for stream 'ba0e30df-1c45-43b9-8077-626173f74d3a'.

This is something I was looking to achieve. 
Thank you so much Greg and James for your help and prompt replies.

**Comment by ChrisChinchilla** [comment]
For the original comment.

**Comment by haf** [comment]
```bash
#!/usr/bin/env bash
set -o pipefail
set -e

export ADMIN_PASSWORD='j&p{[3cNzR24#=*J&d96>6;4678^zE'

cat >eventstore-default-acl.json <<"EOF"
[{
  "data": {
    "$userStreamAcl" : {
      "$r"  : ["$admin", "$ops", "service-a", "service-b"],
      "$w"  : ["$admin", "$ops", "service-a", "service-b"],
      "$d"  : ["$admin", "$ops"],
      "$mr" : ["$admin", "$ops"],
      "$mw" : ["$admin", "$ops"]
    },
    "$systemStreamAcl" : {
      "$r"  : "$admins",
      "$w"  : "$admins",
      "$d"  : "$admins",
      "$mr" : "$admins",
      "$mw" : "$admins"
    }
  },
  "eventId": "89466709-6709-6709-6709-153289466709",
  "eventType": "ACL",
  "metadata": {}
}]
EOF

curl -u 'admin:changeit' -F "newPassword=$ADMIN_PASSWORD" -X POST http://localhost:2113/users/admin/command/change-password

curl -i -u "admin:$ADMIN_PASSWORD" \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{"fullName":"Serice A", "groups":[], "loginName":"service-a","password":"b2{[/628)4XK^3t2@K,66?y8Neb=x+' \
  -X POST http://localhost:2113/users/

curl -i -u "admin:$ADMIN_PASSWORD" \
  -H "Content-Type: application/json; charset=utf-8" \
  -d '{"fullName":"Service B", "groups":[], "loginName":"service-b","password":"9n[9CgV*9P4En74F[/x#;%)=g7326*' \
  -X POST http://localhost:2113/users/

curl -i -u "admin:$ADMIN_PASSWORD" \
  -H "Content-Type: application/vnd.eventstore.events+json" \
  -H "Accept: application/json" \
  -d @eventstore-default-acl.json \
  -X POST http://localhost:2113/streams/%24settings
```

**Comment by ChrisChinchilla** [comment]
Thanks @haf I'll look through this soon :)
