### ISSUE TITLE
Docs TODO

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/documentation#164]
Some listings of things worth documenting.

**Comment by lukaswelte** [comment]
@gregoryyoung I started using EventStore recently and really like it, but the docs lack a lot of information. I would contribute to the docs but therefore I would need to know where I can find the spots in the code (without digging through the complete code). 

My main points are in the HTTP API, I would like a complete endpoint list that shows me where I can do what (e.g. don't currently know if I can post a new projection via HTTP although I think EventStore supports it) and various other things.
The next thing is the query language and what it supports. I know it is JavaScript but JS commands are not evaluated like `Object.assign` and there are internal hooks that I can use e.g. `$init` and `$any` but is there more like `$afterAll`?

If you could provide me with the information where I can quickly find the source code that makes up the HTTP endpoints and the code for the query languages I would be happy to contribute docs of these.

**Comment by pgermishuys** [comment]
As far as projections go, the documentation will be up as part of 4.0.0. 4.0.0 is when projections come out of beta.

**Comment by lukaswelte** [comment]
Great, when is there already some estimate when 4.0 is going to happen @pgermishuys? 

And what about the query language? These two are really things slowing me down working with the 3.9 version

**Comment by pgermishuys** [comment]
@lukaswelte 4.0.0 is scheduled for the release before the end of the year.
The query language will form part of the documentation that will be released as part of 4.0.0. You can however if you want look at the query language source [here](https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.Projections.Core/Prelude/1Prelude.js) to see how a projection is constructed.

If you have any specific questions, you are more than welcome to ask them and we'll happily answer them.

**Comment by lukaswelte** [comment]
Awesome, looking forward to it! 👍
