### ISSUE TITLE
Non-async methods still present in docs for 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by jbradford** [EventStore/documentation#18]
http://docs.geteventstore.com/dotnet-api/3.0.0/
http://docs.geteventstore.com/dotnet-api/3.0.0/reading-streams/
http://docs.geteventstore.com/dotnet-api/3.0.0/writing-to-a-stream/

**Comment by ChrisChinchilla** [comment]
This is a fairly old issue and I'm trying to tidy things up, @rcknight as far as you're aware is this relevant anymore? Are at least the current docs up to date now?
