### ISSUE TITLE
Documentation required for the Query tab

### ISSUE THREAD

**Issue by pgermishuys** [EventStore/documentation#235]

**Comment by scottcate** [comment]
Even the most basic examples here would be helpful as a placeholder for something more in the future. In replace of a full chapter written to support this area of you product. 1 hour of work VS a full sprint. Baby steps would be helpful. Thank you for your consideration. I will even write the doc PRs if I can work with someone of getting the working samples.

**Comment by ChrisChinchilla** [comment]
Thanks @scottcate and @pgermishuys actually I feel like most of the web UI could do with documentation, so will broaden this task.
