### ISSUE TITLE
ClientAPI ExpectedVersion.EmptyStream Value in Documentation Does Not Match Value

### ISSUE THREAD

**Issue by seancarroll** [EventStore/documentation#243]
Documentation within the remark states

> ExpectedVersion.EmptyStream (0) says the stream should exist but be empty when doing the write.

However code has

`public const int EmptyStream = -1;`

**Comment by seancarroll** [comment]
Per Greg

> Can you put this on the documentation repository. Also expected version 0 and expected version -1 are synonyms for each other.
> 
> If I expect version 0 that means there are no previous events. If I expect empty stream I expect no previous events. Both mean the same thing.

**Comment by Narvalex** [comment]
Can you share an URL for that documentation, please? I could not find...

**Comment by gregoryyoung** [comment]
There is a semantic difference between a stream existing and a stream having no events in it. In particular you may have created metadata for the stream which represents that it exists though there are not events in the stream.

**Comment by gregoryyoung** [comment]
@seancarroll I would have to look through the code to verify but I think there is a case where they are not the same. In particular a soft-delete and a recreate though I need to check the code to verify.

**Comment by seancarroll** [comment]
@Narvalex can be found at https://github.com/EventStore/EventStore/blob/853a2ba90ad43a2e9b3a62d1d9be504dbf4e7c52/src/EventStore.ClientAPI/ExpectedVersion.cs#L13.

**Comment by ajgajg1134** [comment]
I believe this portion of the docs is somewhat misleading. In the docs it states for special values: `0 states that the stream should exist but should be empty.` However when creating a new stream with the first event, the very first event number is `0` so to post the next event one must set the `ES-ExpectedVersion` header to `0` even though there is an event in the stream, directly contradicting what is written in the docs.

I'm not sure what the best way to re-word this is, but it's my understanding that in the version 4 and up in EventStore there isn't really a way to create a stream with no events in it? (Either way a re-word of some kind would be nice)

**Comment by gregoryyoung** [comment]
You can create a stream with no events in it. Set metadata on it. It will exist but be empty.

**Comment by dgchurchill** [comment]
I think this behaviour changed in [this commit](https://github.com/EventStore/EventStore/commit/47dee1310ded5e665a9825f4d5832dac95d2a6a5#diff-45db67eed5ae6b800c8ffbab8cc356c1L62), which changed the `EmptyStream` constant value from `0` to `-1`. This also means that both `EmptyStream` and `NoStream` must have identical behaviour -- they can't be distinguished.

Note also that `http-api/creating-writing-a-stream.md` has the line:
> 0 states that the stream should exist but should be empty.

This appears to be incorrect in light of the above.
