### ISSUE TITLE
Metadata stream

### ISSUE THREAD

**Issue by teivah** [EventStore/documentation#270]
Hey,

In my humble opinion, the page [Metadata and Reserved Names](https://eventstore.org/docs/server/metadata-and-reserved-names/index.html) should explicitly mention that the metadata stream of a stream called ```foo``` is ```$$foo```. This way it would help the user in setting up ```$maxAge```, ```$maxCount``` etc.

Thanks!

**Comment by ChrisChinchilla** [comment]
OK thanks @teivah I'll take a look into this asap :)
