### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by teivah** [EventStore/documentation#271]
Hey,

Every single statistic collected in the ```$stats-...``` stream should be documented. As an user, I had to go to https://github.com/valeriob/EventStore-1/blob/master/src/EventStore/EventStore.Core/Services/Monitoring/SystemStatsHelper.cs

For example, what does ```proc-cpuScaled``` or ```proc-contentionsRate``` concretely mean? I couldn't tell.

Thanks

**Comment by ChrisChinchilla** [comment]
Thanks again @teivah I'll get to this as soon as I can :)

**Comment by ChrisChinchilla** [comment]
Partially done in code documentation, will be more to cover those that are missing and then a doc containing all.

**Comment by ChrisChinchilla** [comment]
<img width="1024" alt="Screenshot 2019-06-28 13 50 04" src="https://user-images.githubusercontent.com/42080/60440491-3e00d900-9c15-11e9-852c-7df15a8d6640.png">
