### ISSUE TITLE
LDAP Integration

### ISSUE THREAD

**Issue by venkatjk** [EventStore/documentation#292]
Planning to integrate with LDAP integration with eventstore. Can you please advise on the right documentation on this.

**Comment by ChrisChinchilla** [comment]
Hey @venkatjk what kind of docs do you think you need?

You can find HTTP and .NET API docs here - https://eventstore.org/docs/ is there anything specific you are missing?

**Comment by ChrisChinchilla** [comment]
Ah right, sorry. Yes LDAP integration is only available in the commercial version @venkatjk 

Here if you have an account - https://developers.eventstore.org/tools/ldap/
