### ISSUE TITLE
Leverage DocFX code highlight feature

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/documentation#314]
To show specific areas of code when docs mention them

**Comment by ChrisChinchilla** [comment]
@StarfallProjects Here's a good one to also learn the features DocFX offers.

There are a handful of code examples littered through out the docs, specifically getting started where the code is included from an external file (the two sample projects mentioned in the documentation build read me), in certain cases, the examples is long, and it may not be clear exactly what line we want to draw the reader's attention to. Let's use the DocFX highlight feature (https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#code-snippet) to do that.

**Comment by StarfallProjects** [comment]
PR: https://github.com/EventStore/documentation/pull/368
