### ISSUE TITLE
the link "Index Rebuilds" point to the wrong page

### ISSUE THREAD

**Issue by riccardone** [EventStore/documentation#315]
**Describe the bug**
the link "Index Rebuilds" in the documentation menu on the public website point to the wrong page "deleting-streams-and-events"

**To Reproduce**
1. Go to https://eventstore.org/docs/
2. Click on 'Server->IndexRebuilds'
3. See the wrong page

**Expected behavior**
The right page to be open

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by ChrisChinchilla** [comment]
Closed in https://github.com/EventStore/documentation/commit/d759e7ab383f6608efaab3db90a774aec9f7035c not even sure how it got there 🤔
