### ISSUE TITLE
Search results not accurate

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/documentation#322]
Search results don't always seem to return accurate results.

![ad171249-9973-4086-84d6-ff97b6214104](https://user-images.githubusercontent.com/42080/51626569-7f93a680-1f48-11e9-95e3-8f76706b6c85.jpg)

**Comment by StarfallProjects** [comment]
Wanted to track my progress so far, mostly for the sake of my own recall.

After some playing around, it looks like search only returns results for standalone words. For example:

```
Does fwibble show up?
```
Search 'fwibble': returns the page

```
Does fwibble(x) show up?
```
Search 'fwibble': no results
^ this example affects our docs a lot, as things like 'DeleteStreamAsync' are usually written as - and thus added to the index.json as - 'DeleteStreamAsync(someOtherStuff)'. This is why we are seeing the failures we are.

```
Does fwibblesomething show up?
```
Search 'fwibble': no results

The page is returned correctly if you do a wildcard search:
```
Does fwibblesomething show up?
```
Search 'fwibble*': returns the page

Options:
- Make no changes, advise users to use wildcard search
- Somehow force lunr.js to always do a wildcard search by default (I am investigating this)

**Comment by StarfallProjects** [comment]
@ChrisChinchilla I have come up with a way to do this by modifying the docfx.js file in es-docs-template. Is this a safe thing to do?

**Comment by StarfallProjects** [comment]
Notes:
- Suggest only enforcing term* wildcard searches. There are comments on lunr.js issues suggesting that *term* would lead to slow searches.

**Comment by ChrisChinchilla** [comment]
@StarfallProjects Yeah, it's relatively safe (I've done it), just as long as it's tested :)

**Comment by StarfallProjects** [comment]
So forcing a wildcard search is simple. However this then breaks other things multi-word searches. I investigated and it looks like this _isn't_ due to stemming. Probably due to [how lunr.js treats whitespace](https://github.com/olivernn/lunr.js/issues/366#issuecomment-409715267). Unfortunately we can't use query rather than search, because it requires a function, which we can't use in a service worker ([can't be cloned](https://stackoverflow.com/a/46145497/2291838))

Also, note a [typo in Docfx's search-worker.js](https://github.com/dotnet/docfx/issues/5038) --- make sure to upgrade to at least 2.45.1

**Comment by StarfallProjects** [comment]
https://github.com/olivernn/lunr.js/issues/421

**Comment by StarfallProjects** [comment]
Am now fairly sure my issue is the wildcard is not matching to whitespace (it's the only thing I can think of that explains all the results I've seen - more details in the lunr.js issue linked above)

**Comment by StarfallProjects** [comment]
search-worker.js has not been customised as far as I can see - at least, it is not in es-docs-template? It seems to be one of the files auto-generated by DocFX. Updating my installed version of DocFX picked up their fix.

**Comment by ChrisChinchilla** [comment]
> search-worker.js has not been customised as far as I can see - at least, it is not in es-docs-template? It seems to be one of the files auto-generated by DocFX. Updating my installed version of DocFX picked up their fix.

That should be the same in the production versions then, as I always have the most up to date. If this gets too messy, might be worth looking at something like Agolia instead?

**Comment by StarfallProjects** [comment]
From James Nugent: searching ‘stats’ give me a ton of APIs but nothing that explains the collectino interval etc
CW response: Maybe we can search tags or something, or switch out to Agolia instead or somesuch

**Comment by StarfallProjects** [comment]
So for the original problem, I'm suggesting we customise search-worker.js in es-docs-template, (including fixing the typo - it crept back in today, and digging through DocFX releases is painful). Add () to the lunr.tokenizer.separator (let's have a think about other characters we want it to split on)

**Comment by ChrisChinchilla** [comment]
@StarfallProjects Now I look at Jame's comment I realise that maybe that particular piece of information just isn't documented. Will create a seperate issue for that. Do you think we should draw up a list of terms to test with?

**Comment by StarfallProjects** [comment]
Yes, good idea.
So here's the branch with my proposed fix: https://github.com/EventStore/es-docs-template/tree/improveSearch (wip)

And here's some suggested term tests with desired results: https://docs.google.com/document/d/1MuLD3ecvtUflXhL1F_GFp3fzSxJHV7W98mOsplVi9qk/edit?usp=sharing

**Comment by StarfallProjects** [comment]
https://github.com/olivernn/lunr.js/issues/424

**Comment by StarfallProjects** [comment]
There was a really useful discussion on the WTD slack about search, which I've captured here in case we need it in future: https://docs.google.com/document/d/1eWLynFGUTUYsh-DhMRTVn5SnjwnwmMe73tA2Veb8Tak/edit?usp=sharing

**Comment by StarfallProjects** [comment]
From above:

> I'd recommend providing a custom, camel-case-aware tokenizer function to the lunr builder - I think you'd have better luck with that.
> 
> However, I've noticed a few of your issues seem to revolve around searching source code, and I'm not sure lunr is particularly well-suited to that. Is there a specific reason you chose lunr?

A couple of questions come out of this:

1. What search (if any) does mdBook's default theme provide?
2. If we are shifting tooling to one tool for all docs, should we also re-evaluate the search provider at the same time?

**Comment by ChrisChinchilla** [comment]
> What search (if any) does mdBook's default theme provide?

Seems to be elasticlunr, some sort of lunr / elastic search hybrid

> If we are shifting tooling to one tool for all docs, should we also re-evaluate the search provider at the same time?

I'm not sure we are…

I kind of like the idea of one of the services that gives us a unified experience across all "sites" and analytics will be useful for the marketing hires. Want to do a bit of analysis for presentation?
