### ISSUE TITLE
Advertised /user endpoint results in 404

### ISSUE THREAD

**Issue by chewiedog** [EventStore/documentation#338]
**Describe the bug**
Documentation states that to get a list of all users:
`/users`
is the endpoint. This will return a 404 Not Found.
The actual endpoint requires the trailing slash: 
`/users/`
this will return the desired list of users.
 

**To Reproduce**
1. Go to `/users`
2. See 404 Not found error

**Expected behavior**
endpoint should return a list of all users.

**Additional context**
This behavior was observed using Eventstore 4.1.1

**Comment by ChrisChinchilla** [comment]
Thanks @chewiedog fixed in https://github.com/EventStore/documentation/pull/339
