### ISSUE TITLE
Add further explanations to getting started guide code examples

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/documentation#353]
There are a coupe of places in the getting started guide where the code examples could do with further explanation, or at least links to where the reader can find further explanation. For example.

<img width="739" alt="Screen_Shot_2019-05-24_at_13 18 49" src="https://user-images.githubusercontent.com/42080/60251076-2b5e6b00-98c8-11e9-8f32-ac58ca521de8.png">

**Comment by ChrisChinchilla** [comment]
Here's another getting started improvement @StarfallProjects I will leave this somewhat up to you, the screenshot above shows one, but basically anywhere where a concept is mentioned in passing through code examples or text and there's a an opportunity to add more information, let's do it. This could be via a simple link, or with a popout box. Make sure you check the DocFX docs for how to do this, as they have some features that handle links differently, and the popouts are a feature of their custom markdown syntax.

**Comment by ChrisChinchilla** [comment]
Here's an example:

Find more details on the parameters used in the example above, read the API documentation for [`PersistentSubscriptionSettings`](xref:EventStore.ClientAPI.PersistentSubscriptionSettings), [`CreatePersistentSubscriptionAsync`](xref:EventStore.ClientAPI.IEventStoreConnection.CreatePersistentSubscriptionAsync*) and [`ConnectToPersistentSubscription`](xref:EventStore.ClientAPI.IEventStoreConnection.ConnectToPersistentSubscriptionAsync*)

**Comment by StarfallProjects** [comment]
PR: https://github.com/EventStore/documentation/pull/369
