### ISSUE TITLE
How do I diable stats on using config file?

### ISSUE THREAD

**Issue by AndreSteenbergen** [EventStore/documentation#358]
When I check my chunk files using less I can find a lot of statsCollected events, followed by u huge json part. It is actually more than my real data. I do need projections, but I can live without logged stats, going back since the first start.

I am on ubuntu, and I installed using the repositories. Hope someone can help.

**Comment by hayley-jean** [comment]
You can set the `StatsPeriodSec` config value to a very high number.
You can find information about this [here](https://eventstore.org/docs/server/command-line-arguments/index.html#application-options) in the docs. 

If you want to remove the stats that have already been written, you can decrease the `$maxAge` metadata of the stats stream and run a scavenge. By default the stats will be kept for 24 days.

You can find information about setting stream metadata [here](https://eventstore.org/docs/dotnet-api/stream-metadata/index.html#writing-metadata).

**Comment by AndreSteenbergen** [comment]
thx
