### ISSUE TITLE
Separate installing and building docs

### ISSUE THREAD

**Issue by ChrisChinchilla** [EventStore/documentation#361]
Some areas of the user docs have mentions of building rather than using EventStore, we should either create separate docs for that, or forward people to the GitHub repo and polish the docs there.

Mostly this line

> Windows platform SDK with compilers (v7.1) or Visual C++ installed (Only required for a full build)

But might be more, and also worth checking that prerequisites mentioned are actually for using and not for building ES.

**Comment by StarfallProjects** [comment]
First PR (docs) https://github.com/EventStore/documentation/pull/370
Next step is to review and edit the build instructions in the README here: https://github.com/EventStore/EventStore

**Comment by StarfallProjects** [comment]
Have hit an issue working through the Linux instructions (had got it working on Windows). 

Asked the following in Slack, but duplicating here for reference:

> Have hit a glitch on Linux:
> error MSB4018: The "Microsoft.Build.Tasks.Git.LocateRepository" task failed unexpectedly.
> I'm using the correct Mono and Core .NET SDK versions. I'm on WSL (Ubuntu 18)
> It looks like it's a somewhat known issue, but I am not finding a workaround/fix:
> https://github.com/Microsoft/fhir-server/issues/262
> https://github.com/dotnet/sourcelink/issues/155

**Comment by ChrisChinchilla** [comment]
@StarfallProjects can confirm I get the same error (and more) with 18.04 in a VM too. paging @shaan1337

**Comment by shaan1337** [comment]
@StarfallProjects @ChrisChinchilla on Ubuntu 18.04, dotnet core has a dependency on libcurl3. Installing it should fix the build issues you're running into:
`sudo apt-get install libcurl3`

This will force libcurl4 to be removed (on which other applications may depend) as both of them cannot coexist. I'm not sure if there's a simpler workaround.

**Comment by StarfallProjects** [comment]
@shaan1337 thanks for this! Is it _only_ Ubuntu 18? (so <16 are ok?)

**Comment by shaan1337** [comment]
@StarfallProjects yup, I've seen it happen only on Ubuntu 18.04

**Comment by ChrisChinchilla** [comment]
Add that to the read me! @StarfallProjects

**Comment by StarfallProjects** [comment]
The README update is here: https://github.com/EventStore/EventStore/pull/1979
