### ISSUE TITLE
"Change Password" API docs missing "currentPassword" field

### ISSUE THREAD

**Issue by Mnuzz** [EventStore/documentation#374]
**Describe the bug**
The docs at https://eventstore.org/docs/http-api/swagger/users/change%20password do not indicate that the field "currentPassword" is required, and does not list the password at all. When trying to change the password following the current documentation to the letter, a cryptic error is thrown in the console and the request will timeout after a full 10 seconds with nothing reported back to the HTTP client. But if including the "currentPassword" field, the command completes successfully.

```
EXCEPTION OCCURRED
String reference not set to an instance of a String.
Parameter name: s
[97472,15,04:30:43.851] Error while processing message EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted in queued handler '"MainQueue"'.
EXCEPTION OCCURRED
String reference not set to an instance of a String.
Parameter name: s
```

**To Reproduce**

Tested on a new install (version 5.0.2 Chocolatey) on Windows with HTTP API

(throws error):
```
POST
http://localhost:2113/users/admin/command/change-password
{
	"newPassword": "a12345"
}
```
(works):
```
POST
http://localhost:2113/users/admin/command/change-password
{
        "currentPassword": "changeit",
	"newPassword": "a12345"
}
```
**Expected behavior**

The documentation and the API should reflect the same requirements. A change to either the documentation or the API is necessary, for the "currentPassword" field.

**Additional context**

I've included recommendations below regarding the other concurrent defects related to this. Should they be in their own issue? 

1) I would recommend taking a bit of effort to investigate how this happened in the first place, as if it can happen once it can happen elsewhere too. Having documentation that doesn't reflect the actual state of the API is a pretty serious problem, so if there was a process or procedure or lack thereof that caused this to happen, that would also be a critical bug in my opinion. 

2) When a required parameter is missing, the error should be handled and displayed to the HTTP client in some form of message. Currently, the console (or default logger) displays a cryptic error and the request times out. 

3) Consider investigating the logic around unhandled error conditions with HTTP API calls and implement some kind of catch-all to report to the client that an unknown error occurred. 

4) Strongly recommend publishing the API docs/spec with version info (including past versions), or some users will definitely have this problem, and they (or the ES dev team) might forget to double check the user's version when trying to solve the issue. 

Note that items 2 and 3 are different issues. If you fix 3 on its own, the required parameter missing will still show as an unidentified error.  If you fix 2 on its own, there may be other types of errors which will have non-graceful failures as this did.

**Comment by ChrisChinchilla** [comment]
@Mnuzz Thanks.

So, the syntax of the underlying Swagger file was mostly correct, but rendering incorrectly through DocFX, and it's template needs some tweaking (which I had in progress for other reasons). I'll fix up some minor issues with the file too.

The swagger file was created long after the code, and is updated manually, while I agree with you this is bad practise, I am not going to be able to convince our dev team to generate it from code any time soon.

I am looking into maintaining versions of the docs again, but they were removed a little while ago as things don't change that much, but it's on the list to bring back.

**Comment by ChrisChinchilla** [comment]
Now fixed!
