### ISSUE TITLE
Improve documentation around updating backups after scavenging

### ISSUE THREAD

**Issue by Lougarou** [EventStore/documentation#450]
To improve documentation around guidelines/best practices to perform a backup and to update the backup after a scavenge operation has completed.

**Comment by alexeyzimarev** [comment]
Dude, we aren't doing anything _here_ :)

![image](https://user-images.githubusercontent.com/2821205/96569555-9572fe80-12c9-11eb-9999-06cd925c1f4d.png)

**Comment by Lougarou** [comment]
Oops
