### ISSUE TITLE
API reference and .NET API docs

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#86]
I see that a lot of things in the existing .NET API documentation would benefit from direct include from auto-generated docs. For example, parameters and syntax might change in the code and be properly updated in the API reference, but the markdown page will not be updated.

I think there are two options:
 - Use some kind of include to directly take a part of the generated reference and insert it to the docs page
 - Avoid listing class members and method parameters altogether and concentrate on describing how it works. Reference the API docs if necessary.

@mat-mcloughlin thoughts?

**Comment by mat-mcloughlin** [comment]
closing for #338
