### ISSUE TITLE
Improve subscriptions documentation

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#90]
Move away from the method-style documentation since methods and parameters are documented in the generated code docs (triple-slash comments). Provide some meaningful description of what developers need to do to use EventStoreDB in their applications instead, with comprehensive code samples.

[ ] Clean up confusing terminology: competing consumers vs persistent subscriptions vs consumer groups
[ ] Add catch-up subscriptions docs
[ ] Add proper examples

**Comment by oskardudycz** [comment]
We're also missing this section for v20.

**Comment by alexeyzimarev** [comment]
That's different as the gRPC docs are a different story.

**Comment by oskardudycz** [comment]
@alexeyzimarev do we still need to do it? What's a priority in your opinion?
