### ISSUE TITLE
Docs for different deployment scenarios

### ISSUE THREAD

**Issue by jbradford** [EventStore/documentation#91]
Do we want to have pages in the new docs for different common deployment scenarios (Azure, Amazon, etc.), or would these deployment guides be better served elsewhere? We previously had pages in the wiki for Azure and currently have an out of date page regarding puppet #89

**Comment by gregoryyoung** [comment]
I think setup pages are highly useful.

On Thursday, January 22, 2015, Jon Bradford <notifications@github.com>
wrote:

> Do we want to have pages in the new docs for different common deployment
> scenarios (Azure, Amazon, etc.), or would these deployment guides be better
> served elsewhere? We previously had pages in the wiki for Azure and
> currently have an out of date page regarding puppet #89
> <https://github.com/EventStore/docs.geteventstore.com/issues/89>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/docs.geteventstore.com/issues/91>.
>


-- 
Studying for the Turing test

**Comment by jen20** [comment]
I'll do the azure one in a minute. It will read "Don't. (No, seriously)."

**Comment by gregoryyoung** [comment]
Lol

**Comment by ChrisChinchilla** [comment]
@gregoryyoung @jen20 As far as I can tell, this isn't done? I am happy to take it on, but might need some guidance further down the line. I'm also thinking that is this better reserved for the HA commercial side of things.

@riccardone any opinions?
