### ISSUE TITLE
Migration plan for v4/5 to v20

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/documentation#95]
We need a page that lists all the necessary steps and changes for the migration. We know that the cluster cannot be upgraded in-flight, so that's the most obvious one. 

@pgermishuys mentioned those:

 - ExtHttpPort, IntHttpPort which is now HttpPort
 - The requirement of the TrustedRootCertificatesPath  as well as the certificates
 - 5.0.8 clients will only work with valid certificates as noted in the Existing TCP clients section in the release notes

I will add the page and hunt some points from the release notes. We can iterate and add more things that are potentially got lost there.

**Comment by alexeyzimarev** [comment]
@Lougarou looks like we also need v3 -> guidelines :)

https://discuss.eventstore.com/t/upgrade-ges-from-3-8-to-5/2755

**Comment by mat-mcloughlin** [comment]
This is all correct but we probably need to call out for people to come speak to us if they need an online upgrade

**Comment by mat-mcloughlin** [comment]
closing in place of https://github.com/EventStore/documentation/issues/436
